# Form implementation generated from reading ui file 'd:\TekkenBot\1.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(414, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 171, 71))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_p1 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_p1.setGeometry(QtCore.QRect(10, 40, 67, 17))
        self.radioButton_p1.setObjectName("radioButton_p1")
        self.radioButton_p2 = QtWidgets.QRadioButton(parent=self.groupBox)
        self.radioButton_p2.setGeometry(QtCore.QRect(80, 40, 81, 17))
        self.radioButton_p2.setChecked(True)
        self.radioButton_p2.setObjectName("radioButton_p2")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 151, 16))
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 221, 51))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_punishBot_on = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton_punishBot_on.setGeometry(QtCore.QRect(10, 20, 91, 17))
        self.radioButton_punishBot_on.setObjectName("radioButton_punishBot_on")
        self.radioButton_punishBot_off = QtWidgets.QRadioButton(parent=self.groupBox_2)
        self.radioButton_punishBot_off.setGeometry(QtCore.QRect(120, 20, 101, 17))
        self.radioButton_punishBot_off.setChecked(True)
        self.radioButton_punishBot_off.setObjectName("radioButton_punishBot_off")
        self.label_punish = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_punish.setGeometry(QtCore.QRect(120, 290, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_punish.setFont(font)
        self.label_punish.setText("")
        self.label_punish.setScaledContents(False)
        self.label_punish.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_punish.setObjectName("label_punish")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tekken7 BotGui"))
        self.groupBox.setTitle(_translate("MainWindow", "Player Select"))
        self.radioButton_p1.setText(_translate("MainWindow", "Player 1"))
        self.radioButton_p2.setText(_translate("MainWindow", "Player 2"))
        self.label.setText(_translate("MainWindow", "Select your side"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Punishment"))
        self.radioButton_punishBot_on.setText(_translate("MainWindow", "PunishBot On"))
        self.radioButton_punishBot_off.setText(_translate("MainWindow", "PunishBot Off"))
