# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(414, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 171, 71))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_p1 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_p1.setGeometry(QtCore.QRect(10, 40, 67, 17))
        self.radioButton_p1.setObjectName("radioButton_p1")
        self.radioButton_p2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_p2.setGeometry(QtCore.QRect(80, 40, 81, 17))
        self.radioButton_p2.setChecked(True)
        self.radioButton_p2.setObjectName("radioButton_p2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 151, 16))
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 251, 61))
        self.groupBox_2.setObjectName("groupBox_2")
        self.radioButton_punish_on = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_punish_on.setGeometry(QtCore.QRect(10, 30, 101, 17))
        self.radioButton_punish_on.setObjectName("radioButton_punish_on")
        self.radioButton_punish_off = QtWidgets.QRadioButton(self.groupBox_2)
        self.radioButton_punish_off.setGeometry(QtCore.QRect(120, 30, 111, 17))
        self.radioButton_punish_off.setChecked(True)
        self.radioButton_punish_off.setObjectName("radioButton_punish_off")
        self.label_punish = QtWidgets.QLabel(self.centralwidget)
        self.label_punish.setGeometry(QtCore.QRect(120, 290, 171, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_punish.setFont(font)
        self.label_punish.setText("")
        self.label_punish.setScaledContents(False)
        self.label_punish.setAlignment(QtCore.Qt.AlignCenter)
        self.label_punish.setObjectName("label_punish")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tekken7 BotGui"))
        self.groupBox.setTitle(_translate("MainWindow", "Player Select"))
        self.radioButton_p1.setText(_translate("MainWindow", "Player 1"))
        self.radioButton_p2.setText(_translate("MainWindow", "Player 2"))
        self.label.setText(_translate("MainWindow", "Select your side"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.radioButton_punish_on.setText(_translate("MainWindow", "Punishment On"))
        self.radioButton_punish_off.setText(_translate("MainWindow", "Punishment Off"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
